### ISSUE TITLE
Hacer que la búsqueda en meli se haga en el controller y  no en el javascript.

### ISSUE THREAD

**Issue by ericbrandwein** [lucasr20/lefrage#28]

**Comment by lucasr20** [comment]
Solo para los stats

**Comment by ericbrandwein** [comment]
No hace falta hacerla para todo lo que traemos? O sea para los stats usamos lo que traemos antes. Si lo hacemos para los stats lo hacemos para todos.

**Comment by ericbrandwein** [comment]
Hecha una búsqueda en la api desde el search service aparte de la que se hace en javascript commit 91926a56e569244977fed5bcb44fdbf3df87ddc4
